import type { RunStatus } from './contracts';

export type Locale = 'ru' | 'en';

export const COPY = {
  ru: {
    title: 'flowcairn',
    subtitle: 'От задачи до проверенного результата.',
    runs: 'Запуски',
    active: 'Активные',
    archive: 'История',
    create: 'Новая задача',
    createCompact: '+ Задача',
    noRuns: 'Опишите, что нужно сделать. Здесь появится план работы.',
    loading: 'Загружаем сохраненное состояние…',
    retryLoad: 'Повторить загрузку',
    graph: 'Граф выполнения',
    fitAll: 'Весь граф',
    focusCurrent: 'Текущий этап',
    details: 'Детали',
    selectNode: 'Выберите этап, чтобы увидеть права, результаты и доступные действия.',
    run: 'Запустить',
    retry: 'Повторить',
    recover: 'Восстановить',
    stop: 'Остановить',
    rerunCheck: 'Повторить проверку',
    replan: 'Новая версия плана',
    receipt: 'Открыть отчет',
    history: 'Изменения',
    plan: 'План',
    evidence: 'Результаты',
    overview: 'Обзор',
    attempt: 'Попытка',
    duration: 'Длительность',
    mode: 'Режим',
    read: 'Чтение',
    write: 'Запись',
    permissions: 'Права',
    skills: 'Инструкции',
    dependencies: 'Зависимости',
    changes: 'Измененные файлы',
    checks: 'Проверки',
    none: 'Нет',
    unavailable: 'Недоступно',
    integrity: 'Целостность',
    healthy: 'Подтверждена',
    runner: 'Исполнитель',
    compare: 'Сравнить план',
    noDiff: 'Структура планов совпадает.',
    compareLoading: 'Загружаем план для сравнения…',
    compareFailed: 'Не удалось загрузить план для сравнения.',
    refresh: 'Обновить',
    language: 'На английском',
    theme: 'Сменить тему',
    live: 'На связи',
    disconnected: 'Обновляем состояние',
    operationFailed: 'Операция не подтверждена',
    retrySame: 'Повторить тот же запрос',
    dismiss: 'Закрыть',
    gateTitle: 'Подтвердите решение',
    approve: 'Подтвердить план',
    accept: 'Принять результат',
    reject: 'Отклонить',
    confirmation: 'Я проверил границы задачи, риски, результаты и последствия.',
    reason: 'Причина отклонения',
    submitDecision: 'Зафиксировать решение',
    cancel: 'Отмена',
    scope: 'Границы задачи',
    risks: 'Риски',
    consequences: 'Последствия',
    planHash: 'Хеш плана',
    draftTitle: 'Черновик новой версии',
    draftHint: 'Редактируется только копия этапов. Активный план остается неизменяемым.',
    validateReplan: 'Отправить на серверную проверку',
    invalidJson: 'Исправьте JSON черновика перед отправкой.',
    status: 'Статус',
    revision: 'Ревизия',
    updated: 'Обновлен',
    taskHash: 'Хеш задачи',
    missingSession: 'Нет локальной сессии управления',
    missingSessionHint: 'Запустите flowcairn ui --root PROJECT и откройте ссылку из терминала.',
  },
  en: {
    title: 'flowcairn',
    subtitle: 'From your task to a checked result.',
    runs: 'Runs',
    active: 'Active',
    archive: 'History',
    create: 'New run',
    createCompact: '+ New',
    noRuns: 'No runs yet. Create a task with exact scope and acceptance.',
    loading: 'Loading committed state…',
    retryLoad: 'Retry loading',
    graph: 'Execution graph',
    fitAll: 'Fit all',
    focusCurrent: 'Current step',
    details: 'Details',
    selectNode: 'Select a step to inspect permissions, check results, and available actions.',
    run: 'Run',
    retry: 'Retry',
    recover: 'Recover',
    stop: 'Stop',
    rerunCheck: 'Rerun check',
    replan: 'New plan version',
    receipt: 'Open receipt',
    history: 'Changes',
    plan: 'Plan',
    evidence: 'Check results',
    overview: 'Overview',
    attempt: 'Attempt',
    duration: 'Duration',
    mode: 'Mode',
    read: 'Read',
    write: 'Write',
    permissions: 'Permissions',
    skills: 'Skills',
    dependencies: 'Dependencies',
    changes: 'Changed files',
    checks: 'Checks',
    none: 'None',
    unavailable: 'Unavailable',
    integrity: 'Integrity',
    healthy: 'Verified',
    runner: 'Runner',
    compare: 'Compare plan',
    noDiff: 'Plan structures match.',
    compareLoading: 'Loading comparison plan…',
    compareFailed: 'Could not load the comparison plan.',
    refresh: 'Refresh',
    language: 'Русский',
    theme: 'Switch theme',
    live: 'State is updating from the service',
    disconnected: 'Live channel is unavailable; 2-second polling remains active.',
    operationFailed: 'Operation was not confirmed',
    retrySame: 'Retry the same request',
    dismiss: 'Dismiss',
    gateTitle: 'Confirm the decision',
    approve: 'Approve plan',
    accept: 'Accept result',
    reject: 'Reject',
    confirmation: 'I reviewed the scope, risks, check results, and consequences.',
    reason: 'Rejection reason',
    submitDecision: 'Record decision',
    cancel: 'Cancel',
    scope: 'Scope',
    risks: 'Risks',
    consequences: 'Consequences',
    planHash: 'Plan hash',
    draftTitle: 'New version draft',
    draftHint: 'Only a copy of nodes is editable. The active plan remains immutable.',
    validateReplan: 'Send for server validation',
    invalidJson: 'Fix the draft JSON before submitting.',
    status: 'Status',
    revision: 'Revision',
    updated: 'Updated',
    taskHash: 'Task hash',
    missingSession: 'Local control session is missing',
    missingSessionHint:
      'Run flowcairn ui --root PROJECT and open the URL printed in your terminal.',
  },
} as const;

export const STATUS: Record<Locale, Record<RunStatus, string>> = {
  ru: {
    idle: 'Не начат',
    waiting: 'Ожидает решения',
    pending: 'В очереди',
    ready: 'Готов к запуску',
    running: 'Выполняется',
    'waiting-for-human': 'Нужно решение',
    passed: 'Завершен',
    failed: 'Ошибка',
    cancelled: 'Остановлен',
    uncertain: 'Результат неизвестен',
    stale: 'Устарел',
  },
  en: {
    idle: 'Idle',
    waiting: 'Waiting',
    pending: 'Pending',
    ready: 'Ready',
    running: 'Running',
    'waiting-for-human': 'Decision needed',
    passed: 'Passed',
    failed: 'Failed',
    cancelled: 'Cancelled',
    uncertain: 'Needs inspection',
    stale: 'Stale',
  },
};

export function statusLabel(status: RunStatus, locale: Locale, resolutionKind?: 'semantic' | 'process' | null): string {
  return status === 'uncertain' && resolutionKind === 'semantic'
    ? locale === 'ru' ? 'Нужно уточнение' : 'Clarification needed'
    : STATUS[locale][status];
}

export function formatDuration(value: number | null | undefined, locale: Locale = 'ru'): string {
  if (value == null) return '—';
  if (value < 1000) return `${Math.round(value)} ${locale === 'ru' ? 'мс' : 'ms'}`;
  return `${(value / 1000).toFixed(value < 10_000 ? 1 : 0)} ${locale === 'ru' ? 'с' : 's'}`;
}

export function formatDate(value: string | null | undefined, locale: Locale): string {
  if (!value) return '—';
  const date = new Date(value);
  return Number.isNaN(date.getTime())
    ? '—'
    : new Intl.DateTimeFormat(locale === 'ru' ? 'ru-RU' : 'en-US', {
        dateStyle: 'short',
        timeStyle: 'medium',
      }).format(date);
}
